config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: [:sessions , :registrations, :passwords]

  devise_scope :admins do
    namespace :admin do
      resources :movies, only: [:new, :create, :edit, :update, :destroy]
      resources :actors, only: [:new, :create, :edit, :update, :destroy]
      resources :producers, only: [:new, :create, :edit, :update, :destroy]
      resources :directors, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :movies, only: [:index, :show] do
    member do
      post :comment
    end
  end

  resources :actors, only: [:index, :show]
  resources :producers, only: [:index, :show]
  resources :directors, only: [:index, :show]

  root 'dashboard#index', as: :dashboard_index

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @movies     = Movie.limit(4).order(id: :desc)
    @directors  = Director.limit(4).order(id: :desc)
    @actors     = Actor.limit(8).where(type: 'Actor').order(id: :desc)
    @producers  = Producer.limit(4)
  end

end

app/views/dashboard/index.html.haml
%h3.section-title  Latest Movie
.row
  - @movies.each do |movie|
    .col-sm-6.col-md-3
      .latest-movie
        = link_to movie_path(movie) do
          = image_tag url_for(movie.cover), style: "width:100% !important; height:200px !important;"
        %h5.section-title.text-center.mt-4
          = link_to movie.title, movie_path(movie)
        %p.text-center.bold Rating #{movie.rating}/5
      - if current_admin.present?
        .row.mb-5
          .col-md-9{style: 'margin-left: 76px'}
            = link_to "Edit",   edit_admin_movie_path(movie), class: 'btn btn-sm btn-info'
            = link_to "Destroy", admin_movie_path(movie), method: :delete,  class: 'btn btn-sm btn-danger',:data => {:confirm => 'Are you sure?'}

.row
  .col-md-6.mb-5
    = link_to 'See more', movies_path, class: 'btn btn-md btn-primary mt-3 float-right'


%h3.section-title.mt-4  Director
.row
  - @directors.each do |director|
    .col-sm-6.col-md-3
      .latest-movie
        = link_to director_path(director) do
          - if director.avatar.present?
            = image_tag url_for(director.avatar), style: "width:100% !important; height:200px !important;"
        %h5.section-title.text-center.mt-4
          = link_to director.fullname, director_path(director)
        %p.text-center.bold
      - if current_admin.present?
        .row.mb-5
          .col-md-9{style: 'margin-left: 76px'}
            = link_to "Edit",   edit_admin_director_path(director), class: 'btn btn-sm btn-info'
            = link_to "Destroy", admin_director_path(director), method: :delete,  class: 'btn btn-sm btn-danger',:data => {:confirm => 'Are you sure?'}

.row
  .col-md-6.mb-5
    = link_to 'See more', directors_path, class: 'btn btn-md btn-primary mt-3 float-right'



%h3.section-title.mt-4    Producer
.row
  - @producers.each do |producer|
    .col-sm-6.col-md-3
      .latest-movie
        = link_to producer_path(producer) do
          - if producer.avatar.attached?
            = image_tag url_for(producer.avatar), style: "width:100% !important; height:200px !important;"
        %h5.section-title.text-center.mt-4
          = link_to producer.fullname, producer_path(producer)
        %p.text-center.bold
      - if current_admin.present?
        .row.mb-5
          .col-md-9{style: 'margin-left: 76px'}
            = link_to "Edit",   edit_admin_producer_path(producer), class: 'btn btn-sm btn-info'
            = link_to "Destroy", admin_producer_path(producer), method: :delete,  class: 'btn btn-sm btn-danger',:data => {:confirm => 'Are you sure?'}


.row
  .col-md-6.mb-5
    = link_to 'See more', producers_path, class: 'btn btn-md btn-primary mt-3 float-right'


%h3.section-title.mt-4  Actor
.row
  - @actors.each do |actor|
    .col-sm-6.col-md-3
      .latest-movie
        = link_to actor_path(actor) do
          - if actor.avatar.attached?
            = image_tag url_for(actor.avatar), style: "width:100% !important; height:200px !important;"
        %h5.section-title.text-center.mt-4
          = link_to actor.fullname, actor_path(actor)
        %p.text-center.bold
      - if current_admin.present?
        .row.mb-5
          .col-md-9{style: 'margin-left: 76px'}
            = link_to "Edit",   edit_admin_actor_path(actor), class: 'btn btn-sm btn-info'
            = link_to "Destroy", admin_actor_path(actor), method: :delete,  class: 'btn btn-sm btn-danger',:data => {:confirm => 'Are you sure?'}
.row
  .col-md-6.mb-5
    = link_to 'See more', actors_path, class: 'btn btn-md btn-primary mt-3 float-right'