config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: [:sessions , :registrations, :passwords]

  devise_scope :admins do
    namespace :admin do
      resources :movies, only: [:new, :create, :edit, :update, :destroy]
      resources :actors, only: [:new, :create, :edit, :update, :destroy]
      resources :producers, only: [:new, :create, :edit, :update, :destroy]
      resources :directors, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :movies, only: [:index, :show] do
    member do
      post :comment
    end
  end

  resources :actors, only: [:index, :show]
  resources :producers, only: [:index, :show]
  resources :directors, only: [:index, :show]

  root 'dashboard#index', as: :dashboard_index

end

app/models/director.rb
class Director < Actor

  # relationship
  has_one_attached :avatar

  # validation
  validates :avatar,  presence: true


  # scope
  scope :search,  ->(search) {
    collection = self

    if search.present?
      collection = collection.where(" (fullname LIKE :search) OR (city LIKE :search)", search: "%#{search}%")
    end

    collection
  }

end

app/controllers/admin/directors_controller.rb
class Admin::DirectorsController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :find_director, only: [:edit, :update, :destroy]

  def new
    @director = Director.new
  end

  def create
    @director = current_admin.directors.new(director_params)

    if @director.save
      flash[:notice] = "#{@director.fullname} has been created"
      redirect_to director_path(@director)
    else
      flash[:error] = @director.errors.full_messages.join("<br />").html_safe
    end
  end

  def edit; end

  def update
    if @director.update(director_params)
      flash[:notice] = "#{@director.fullname} has been updated"
      redirect_to director_path(@director)
    else
      flash[:error] = @director.errors.full_messages.join("<br />").html_safe
    end
  end

  def destroy
    @director.destroy!
  end


  def director_params
    params.require(:director).permit(:fullname, :biografi, :born, :city, :avatar)
  end

  private

  def find_director
    @director = current_admin.directors.find(params[:id])
  end


end

app/controllers/directors_controller.rb
class DirectorsController < Admin::BaseController
  before_action :find_director, only: [:show]

  def index
    @directors = Director.search(params_search).order(id: :desc)
  end

  def show; end

  private

  def find_director
    @director = Director.find(params[:id])
  end

  def params_search
    params[:search]
  end

end

app/views/directors/index.html.haml
%h3.section-title.mt-4  Director
.row.mb-5
  .col-md-12
    .col-md-6
      = simple_form_for  :search, url: directors_path, :method => :get,  :html => {:multipart => true, :class => 'form-horizontal float-right'}, wrapper: :horizontal_input_group do |f|
        = f.input :search, input_html: { name: 'search'}
        .float-right.mr-4
          = f.submit

    .col-md-6
      - if current_admin.present?
        = link_to "Add director", new_admin_director_path, class: "btn btn-md btn-primary"

.row
  - @directors.each do |director|
    .col-sm-6.col-md-3
      .latest-movie
        = link_to director_path(director) do
          - if director.avatar.present?
            = image_tag url_for(director.avatar), style: "width:100% !important; height:200px !important;"
        %h5.section-title.text-center.mt-4
          = link_to director.fullname, director_path(director)
        %p.text-center.bold
      - if current_admin.present?
        .row.mb-5
          .col-md-9{style: 'margin-left: 76px'}
            = link_to "Edit",   edit_admin_director_path(director), class: 'btn btn-sm btn-info'
            = link_to "Destroy", admin_director_path(director), method: :delete,  class: 'btn btn-sm btn-danger',:data => {:confirm => 'Are you sure?'}

app/views/directors/show.html.haml
.breadcrumbs
  %a{:href => "index.html"} Home
  %a{:href => "#"} #{@director.fullname}

.content
  .row
    .col-md-6
      %figure.movie-poster
        = image_tag url_for(@director.avatar), style: "width:100% !important; height:650px !important;"

    .col-md-6
      %h2.movie-title
        = @director.fullname
      .movie-summary
        %p
          = @director.biografi

      %ul.movie-meta
        %li
          %strong born: #{born_helper(@director.born)}

        %li
          %strong city: #{@director.city}