config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: [:sessions , :registrations, :passwords]

  devise_scope :admins do
    namespace :admin do
      resources :movies, only: [:new, :create, :edit, :update, :destroy]
      resources :actors, only: [:new, :create, :edit, :update, :destroy]
      resources :producers, only: [:new, :create, :edit, :update, :destroy]
      resources :directors, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :movies, only: [:index, :show] do
    member do
      post :comment
    end
  end

  resources :actors, only: [:index, :show]
  resources :producers, only: [:index, :show]
  resources :directors, only: [:index, :show]

  root 'dashboard#index', as: :dashboard_index

end

app/models/producer.rb
class Producer < Actor

  # relationship
  has_one_attached :avatar

  # validation
  validates :avatar,  presence: true


  # scope
  scope :search,  ->(search) {
    collection = self

    if search.present?
      collection = collection.where(" (fullname LIKE :search) OR (city LIKE :search)", search: "%#{search}%")
    end

    collection
  }


end

app/controllers/admin/producers_controller.rb
class Admin::ProducersController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :find_producer, only: [:edit, :update, :destroy]

  def new
    @producer = Producer.new
  end

  def create
    @producer = current_admin.producers.new(producer_params)

    if @producer.save
      flash[:notice] = "#{@producer.fullname} has been created"
      redirect_to producer_path(@producer)
    else
      flash[:error] = @producer.errors.full_messages.join("<br />").html_safe
    end

  end

  def edit; end

  def update
    if @producer.update(producer_params)
      flash[:notice] = "#{@producer.fullname} has been updated"
      redirect_to producer_path(@producer)
    else
      flash[:error] = @producer.errors.full_messages.join("<br />").html_safe
    end

  end

  def destroy
    @producer.destroy!
  end

  def producer_params
    params.require(:producer).permit(:fullname, :biografi, :born, :city,
                                  :avatar)
  end

  private

  def find_producer
    @producer = current_admin.producers.find(params[:id])
  end

end

app/controllers/producers_controller.rb
class ProducersController < Admin::BaseController
  before_action :find_producer, only: [:show]

  def index
    @producers = Producer.search(params_search).order(id: :desc)
  end

  def show; end

  private

  def find_producer
    @producer = Producer.find(params[:id])
  end

  def params_search
    params[:search]
  end

end

app/views/producers/index.html.haml
%h3.section-title.mt-4  Producer
.row.mb-5
  .col-md-12
    .col-md-6
      = simple_form_for  :search, url: producers_path, :method => :get,  :html => {:multipart => true, :class => 'form-horizontal float-right'}, wrapper: :horizontal_input_group do |f|
        = f.input :search, input_html: { name: 'search'}
        .float-right.mr-4
          = f.submit

    .col-md-6
      - if current_admin.present?
        = link_to "Add producer", new_admin_producer_path, class: "btn btn-md btn-primary float-right"

.row
  - @producers.each do |producer|
    .col-sm-6.col-md-3
      .latest-movie
        = link_to producer_path(producer) do
          - if producer.avatar.attached?
            = image_tag url_for(producer.avatar), style: "width:100% !important; height:200px !important;"
        %h5.section-title.text-center.mt-4
          = link_to producer.fullname, producer_path(producer)
        %p.text-center.bold
      - if current_admin.present?
        .row.mb-5
          .col-md-9{style: 'margin-left: 76px'}
            = link_to "Edit",   edit_admin_producer_path(producer), class: 'btn btn-sm btn-info'
            = link_to "Destroy", admin_producer_path(producer), method: :delete,  class: 'btn btn-sm btn-danger',:data => {:confirm => 'Are you sure?'}

app/views/producers/show.html.haml
.breadcrumbs
  %a{:href => "index.html"} Home
  %a{:href => "#"} #{@producer.fullname}

.content
  .row
    .col-md-6
      %figure.movie-poster
        = image_tag url_for(@producer.avatar), style: "width:100% !important; height:650px !important;"

    .col-md-6
      %h2.movie-title
        = @producer.fullname
      .movie-summary
        %p
          = @producer.biografi

      %ul.movie-meta
        %li
          %strong born: #{born_helper(@producer.born)}

        %li
          %strong city: #{@producer.city}