config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: [:sessions , :registrations, :passwords]

  devise_scope :admins do
    namespace :admin do
      resources :movies, only: [:new, :create, :edit, :update, :destroy]
      resources :actors, only: [:new, :create, :edit, :update, :destroy]
      resources :producers, only: [:new, :create, :edit, :update, :destroy]
      resources :directors, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :movies, only: [:index, :show] do
    member do
      post :comment
    end
  end

  resources :actors, only: [:index, :show]
  resources :producers, only: [:index, :show]
  resources :directors, only: [:index, :show]

  root 'dashboard#index', as: :dashboard_index

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0,maximum-scale=1", :name => "viewport"}/
    %title Movie Review
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:300,400,700|", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "fonts/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "style.css", :rel => "stylesheet"}/

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body
    #site-content
      %header.site-header
        .container
          %a#branding{:href => "index.html"}
            .logo-copy
              %h1.site-title Simple imdb
              %small.site-description relly simple

          .main-navigation
            %button.menu-toggle{:type => "button"}
              %i.fa.fa-bars
            %ul.menu
              %li.menu-item.current-menu-item
                = link_to "Home", dashboard_index_path
              %li.menu-item
                = link_to "Movies", movies_path
              %li.menu-item
                = link_to "Directors", directors_path
              %li.menu-item
                = link_to "Producers", producers_path
              %li.menu-item
                = link_to "Actor", actors_path
              - if current_admin.present?
                %li.menu-item
                  = link_to 'Logout', destroy_admin_session_path, method: :delete
              - else
                %li.menu-item
                  = link_to 'Sign in', admin_session_path

            %form.search-form{:action => "#"}
              %input{:placeholder => "Search...", :type => "text"}/
              %button
                %i.fa.fa-search

          .mobile-navigation

      %main.main-content
        .container
          .page
            = yield

      %footer.site-footer
        .container
          .colophon Copyright 2014 Company name, Designed by Themezy. All rights reserved

  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = yield :javascript